### ISSUE TITLE
Error thrown when run grunt docs-serve task

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-docs#129] opened 2018-02-05 11:48 UTC
Docs are not built correctly, error is thrown:

```
Building documentation failed: TypeError: /Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/hexo/themes/umberto/layout/_partial/head.pug:13
    11|     if ( ogConfig.description )
    12|         meta( property='og:description' content= page[og-description] || ( ogConfig.description ? ogConfig.description : mainOg.description ) )
  > 13|     if ( ogConfig.image || mainOg.image )
    14|         - const hostname = mainOg.hostname || opConfig.hostname;
    15|         meta( property='og:image' content= hostname + pathJoin(page.latestBasePath || '/', ogConfig.image ? ogConfig.image : mainOg.image) )
    16| 

Cannot read property 'image' of undefined
    at eval (eval at wrap (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:287:31)
    at template (eval at wrap (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:8793:78)
    at TemplateCollection.renderTemplate (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/template/template-collection.js:108:10)
    at ApiBuilder._getPages (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/api-builder/api-builder.js:320:20)
    at ApiBuilder.buildApi (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/api-builder/api-builder.js:101:24)
    at module.exports (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/tasks/build-api-docs.js:55:13)
    at projectConfigs.forEach.config (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/tasks/build-documentation.js:273:19)
    at Array.forEach (native)
    at buildApis (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/tasks/build-documentation.js:256:17)
    at buildProjects (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/tasks/build-documentation.js:189:4)
    at hexoManager.hexoInit.then.then.then.then.then.then (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/src/tasks/build-documentation.js:72:11)
    at tryCatcher (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/comandeer/repos/ckeditor/ckeditor-docs/node_modules/umberto/hexo/node_modules/bluebird/js/release/promise.js:693:18)
```

**Comment by m-turek** [comment] 2018-02-05 13:19
It's duplicate of https://github.com/cksource/umberto/issues/472

**Closed by m-turek** 2018-02-05 13:19 UTC
Labels: bug

**Comment by m-turek** [comment] 2018-02-05 15:24
Fixed with latest Umberto
